kind: pipeline
name: frontend

steps:
  - name: Build
    image: node:8.16.0-stretch
    volumes:
    - name: cypress
      path: /root/.cache/Cypress
    commands:
      - cd frontend
      - npm install

  - name: Lint
    image: node:8.16-stretch
    commands:
      - cd frontend
      - npm run lint

  - name: Unit-Tests
    image: node:8.16-stretch
    commands:
      - cd frontend
      - npm run test:unit
---

kind: pipeline
name: frontend-e2e
steps:
  - name: E2E-Tests
    image: cypress/browsers:node8.15.1-chrome73
    commands:
      - cd frontend
      - npm install
      - npm run test:e2e-ci

---
kind: pipeline
name: backend

steps:
  - name: Build
    image: python:3.7-stretch
    commands:
      - cd backend
      - pip install --upgrade pip
      - pip install pipenv
      - pipenv install --dev --system --deploy

  - name: Lint
    image: python:3.7-stretch
    commands:
      - cd backend
      - pipenv install --dev --system --deploy
      - flake8

  - name: Unit-Test
    image: python:3.7-stretch
    environment:
    commands:
      - cd backend
      - pipenv install --dev --system --deploy
