kind: pipeline
name: frontend

steps:
  - name: Build
    image: node:8.16.0-stretch
    volumes:
    - name: cypress
      path: /root/.cache/Cypress
    commands:
      - cd frontend
      - npm install --no-optional

  - name: Lint
    image: node:8.16-stretch
    commands:
      - cd frontend
      - npm run lint

  - name: Unit-Tests
    image: node:8.16-stretch
    commands:
      - cd frontend
      - npm run test:unit
      
---
kind: pipeline
name: backend

steps:
  - name: Lint
    image: python:3.7-stretch
    commands:
      - cd backend
      - pip install --upgrade pip
      - pip install pipenv
      - pipenv install --dev --system --deploy
      - flake8
